### ISSUE TITLE
Generate HTML templates

### ISSUE THREAD

**Issue by albinomn** [olivere/vite#15]
Is it possible to generate static html templates? or it would require to create a vite plugin?
Do you have something planned for this?

**Comment by olivere** [comment]
Hi! I'm trying to understand. Can you maybe describe the problem or give an example of what you're looking for?

**Comment by albinomn** [comment]
It would be SSG instead of SPA, when building the app it would result in HTML/JS instead of only JS

I don't have a problem for now

**Comment by olivere** [comment]
So the library is for generating and serving HTML on the server-side, in Go, and injecting the bundled assets from Vite/ESBuild. Not sure if that answers your question, but I'm closing it for now.
