### ISSUE TITLE
Allow custom index.html template registration

### ISSUE THREAD

**Issue by ge3224** [olivere/vite#5]
# Allow custom index.html template registration

Currently, it's not possible to register a custom template for the root ("/") and "/index.html" routes without causing a panic. This limitation prevents users from incorporating custom Go templates at the primary entry point of their web applications built with Vite and Go.

## Current Behavior

The `RegisterTemplate` method panics if a template named "index.html" is registered, as it's already registered by default:

```go
// RegisterTemplate registers a template with the handler. Notice that the
// template name must be unique, and "index.html" is already registered by
// default. If the template name is already registered, it panics.
func (h *Handler) RegisterTemplate(name, text string) {
  if h.templates == nil {
    h.templates = make(map[string]*template.Template)
  }
  if _, ok := h.templates[name]; ok {
    panic(fmt.Sprintf("vite: template %q already registered", name))
  }
  h.templates[name] = template.Must(template.New(name).Parse(text))
}
```

Attempting to register a custom index template results in a panic:

```bash
panic: vite: template "index.html" already registered

goroutine 1 [running]:
github.com/olivere/vite.(*Handler).RegisterTemplate(0xc00010b040, {0x7e18fc, 0xa}, {0x7fcb1c, 0x404})
/home/ge/Projects/go-vite/feat/fallback-template/handler.go:134 +0x17d
main.runDevServer()
/home/ge/Projects/go-vite/feat/fallback-template/examples/custom-index/main.go:89 +0x10f
main.main()
/home/ge/Projects/go-vite/feat/fallback-template/examples/custom-index/main.go:26 +0x8d
```

## Proposed Solution

Modify the behavior so that the default template functions as a fallback, only registered if no "index.html" template has been provided by the user. This change would allow users to define custom templates for the root and index routes.

## Example Use Case

Users might want to include custom semantic HTML elements outside their JS/TS application, such as:

```go
var (
  customIndex = `
<!doctype html>
<html lang="en" class="h-full scroll-smooth">
  <head>
    <meta charset="UTF-8" />
  {{- if .Metadata }}
    {{ .Metadata }}
  {{- end }}
  {{- if .IsDev }}
    {{ .PluginReactPreamble }}
    <script type="module" src="{{ .ViteURL }}/@vite/client"></script>
    <script type="module" src="{{ .ViteURL }}/src/main.tsx"></script>
  {{- else }}
    {{- if .StyleSheets }}
    {{ .StyleSheets }}
    {{- end }}
    {{- if .Modules }}
    {{ .Modules }}
    {{- end }}
    {{- if .PreloadModules }}
    {{ .PreloadModules }}
    {{- end }}
  {{- end }}
  {{- if .Scripts }}
    {{ .Scripts }}
  {{- end }}
  </head>
  <body class="min-h-screen antialiased">
    <header>My Custom Header</header>
    <main>
      <div id="root"></div>
      <noscript>
        <div>
          <h2>JavaScript Required</h2>
          <p>This application requires JavaScript to run. Please enable JavaScript
          in your browser settings and reload the page.</p>
        </div>
      </noscript>
    </main>
    <footer>My Unique Footer</footer>
  </body>
</html>
`
)

```

In such cases, users would expect to register their custom index template as they would other templates:

```go
  viteHandler, err := vite.NewHandler(vite.Config{
    FS:      os.DirFS("."),
    IsDev:   true,
    ViteURL: "http://localhost:5173",
  })
  if err != nil {
    panic(err)
  }

  viteHandler.RegisterTemplate("index.html", customIndex)
```

## Implementation Details

I have adjusted this behavior locally in my fork and would be happy to create a pull request for your review. The PR would include an example for testing purposes.

## Next Steps

I'd appreciate your thoughts on this proposed change. If you're open to this modification, I can submit a pull request with the necessary changes and an example for testing. Would you like me to proceed with creating a PR?

**Comment by olivere** [comment]
Yes. That makes sense. It must not panic but replace the already registered default.

I'm still unsure if we should invert the responsibility here. Maybe the application should always define and return templates, and the library should just inject the required Vite scripts. But anyway: That's probably a different issue altogether.

**Comment by ge3224** [comment]
> I'm still unsure if we should invert the responsibility here. Maybe the application should always define and return templates, and the library should just inject the required Vite scripts. But anyway: That's probably a different issue altogether.

That's a good point. We can explore that issue. For now, I've created a pull request that provides some flexibility. You can find the PR here: https://github.com/olivere/vite/pull/6. I've also included a working example.

Let me know your thoughts
